### ISSUE TITLE
Questions about controlled vocabulary usage

### ISSUE THREAD

**Issue by Joonas-M-S** [mobilityDCAT-AP/mobilityDCAT-AP#35] opened 2024-06-13 13:21 UTC
Hi, I have been working on a project to make the metadata conform to MobilityDCAT-AP. I looked into `dct:Distribution` class and how an instance of the class should look like. There are some questions that have sprung to my mind while working on this.

- `dct:Distribution` has a mandatory property `mobilitydcatap:mobilityDataStandard` that has a range of `mobilitydcatap:MobilityDataStandard`. The class `mobilitydcatap:MobilityDataStandard` itself has two properties as per the [documentation](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#properties-for-mobility-data-standard): `owl:versionInfo` and `mobilitydcatap:schema`.
    - There might be a typo in the serialized version of the documentation regarding the domain of [owl:versionInfo](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/ba0949f296c21ced7cc5051cb955535046f29355/releases/1.0.1/mobilitydcat-ap.ttl#L820) being defined as the property `mobilitydcatap:mobilityDataStandard`.
    - The property `mobilitydcatap:schema` has `rdfs:Resource` as the range. I was wondering if there are any recommendations what to put there when creating an instance of a `mobilitydcatap:MobilityDataStandard`? When using the controlled vocabulary, then I guess the value should be some of the `skos:Consept`s provided and the instance could look something like this in Turtle:
    ```Turtle
    [
         a mobilitydcatap:MobilityDataStandard ;
         mobilitydcatap:schema <https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II> ;
         owl:versionInfo "3.2"
    ]
    ```
    but what if a custom standard is used? The usage note on mobility data standard states that:
    
    >  If no established mobility data standard is applied, an information "proprietary standard" is requested.
    
    and in the usage note of the schema states
    
    > The data platform SHOULD keep an archive of commonly used schemas. The data provider SHOULD be able to select an applicable schema from this archive, or to upload an own, individual schema.

    So I guess that in it's simplest form `mobilitydcatap:schema` value could be a Literal containing a URL or free text. But keeping a list of free text fields in a database and presenting them to all users that want to create a Distribution sounds like in a couple of years the list is going to get unwieldy. Especially if we happen to get a malicious user creating these.

    - There is a typo in the usage note of the schema. "There are differet optiions ..."

    
- The property `dct:format` has a range of `dct:MediaTypeOrExtent` and a controlled vocabulary is used. However, the class `dct:MediaTypeOrExtent` does not have any properties defined and the usage note of the controlled vocabulary just states that

    > Values from this vocabulary MUST be used as instances of class dct:MediaTypeOrExtent...

    which sounds like the following, partial example of an instance of a `dct:Distribution`, should do the trick:
    ```Turtle
    [
         a dcat:Distribution ;
         dct:format <http://publications.europa.eu/resource/authority/file-type/XML>
    ]
    ```

     but the [SHACL file](https://github.com/SEMICeu/DCAT-AP/blob/b9b20d1d25e6d827754e93af918344a46dc41a1b/releases/2.0.1/dcat-ap_2.0.1_shacl_shapes.ttl#L603) expects the object to be of type dct:MediaTypeOrExtent which `<http://publications.europa.eu/resource/authority/file-type/XML>` is not. What should I use as an object for the above example?
    
- The property `cnt:characterEncoding` usage notes states that
    
    > A controlled vocabulary § 5.2 Controlled vocabularies to be used is provided.

    but I cannot find one. And the range is defined as `rdfs:Literal` instead of it being a `skos:Concept` as with the other controlled vocabularies

**Comment by peterlubrich** [comment] 2024-08-15 10:45
> There might be a typo in the serialized version of the documentation regarding the domain of [owl:versionInfo](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/ba0949f296c21ced7cc5051cb955535046f29355/releases/1.0.1/mobilitydcat-ap.ttl#L820) being defined as the property mobilitydcatap:mobilityDataStandard.

In mobilityDCAT-AP ReSpec page, it looks like [this](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#mobility-data-standard-version). 

In the mobilityDCAT-AP RDF/XML serialization file, it looks like this:
```
<rdf:Description rdf:about="http://www.w3.org/2002/07/owl#versionInfo">
...
<dcam:domainIncludes rdf:resource="http://w3id.org/mobilitydcat-ap#mobilityDataStandard"/>
<dcam:rangeIncludes rdf:resource="http://www.w3.org/2000/01/rdf-schema#Literal"/>
</rdf:Description>
```
I think the line above should be exchanged to ...
`<dcam:domainIncludes rdf:resource="http://w3id.org/mobilitydcat-ap#MobilityDataStandard"/>`

...so the class "MobilityDataStandard", instead of the property "mobilityDataStandard" is referenced here!

@Daham-Mustaf : please correct the seralisation files accordingly!

**Comment by peterlubrich** [comment] 2024-08-15 11:11
> The property mobilitydcatap:schema has rdfs:Resource as the range. I was wondering if there are any recommendations what to put there when creating an instance of a mobilitydcatap:MobilityDataStandard? When using the controlled vocabulary, then I guess the value should be some of the skos:Consepts provided and the instance could look something like this in Turtle:
> [
>      a mobilitydcatap:MobilityDataStandard ;
>      mobilitydcatap:schema <https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II> ;
>      owl:versionInfo "3.2"
> ]
> but what if a custom standard is used? The usage note on mobility data standard states that:
> 
> If no established mobility data standard is applied, an information "proprietary standard" is requested.
> 
> and in the usage note of the schema states
> 
> The data platform SHOULD keep an archive of commonly used schemas. The data provider SHOULD be able to select an applicable schema from this archive, or to upload an own, individual schema.
> 
> So I guess that in it's simplest form mobilitydcatap:schema value could be a Literal containing a URL or free text. But keeping a list of free text fields in a database and presenting them to all users that want to create a Distribution sounds like in a couple of years the list is going to get unwieldy. Especially if we happen to get a malicious user creating these.

In general, mobilityDCAT-AP expects the following:

- the name of the used standard, e.g. DATEX II
- optional: the version of the used standard , e.g. v3.2
- optional: the schema of the used standard, e.g., a file "DATEXII_3_D2Payload.xsd"

Schema files are important technical artifacts, to be accompanied by a metadata description. They are defined by the data supplier. They can be (depending on the NAP set-up) provided as a static file (...xsd) upload by the data supplier, by a "NAP-internal schema repository", or other means. Further, for some cases, there might even multiple schema files (multiple xsd) (e.g., in DATEX II v3).
So, there are various ways to provide schema file(s) related to a distribution. This is why we decided to use a very generic property "rdfs:Resource" as the range for the schema information. Every NAP deployer should define this on his own. No harmonisation advice on that matter from us so far!

For the coding in TTL, I would take the following:

```
<your URL for the Distribution>
  a dcat:Distribution ;
  mobilitydcatap:mobilityDataStandard <https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II> ,
 ...other properties for this Distribution.

<https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II>
  a mobilitydcatap:MobilityDataStandard ;
  owl:versionInfo "3.2" ,
  mobilitydcatap:schema "...URL leading to schema file(s)..." .
```

**Comment by peterlubrich** [comment] 2024-08-15 11:32
> There is a typo in the usage note of the schema. "There are differet optiions ..."

Just corrected, thanks!

**Comment by peterlubrich** [comment] 2024-08-15 12:59
> The property dct:format has a range of dct:MediaTypeOrExtent and a controlled vocabulary is used. However, the class dct:MediaTypeOrExtent does not have any properties defined and the usage note of the controlled vocabulary just states that
> 
> Values from this vocabulary MUST be used as instances of class dct:MediaTypeOrExtent...
> 
> which sounds like the following, partial example of an instance of a dct:Distribution, should do the trick:
> 
> [
>      a dcat:Distribution ;
>      dct:format <http://publications.europa.eu/resource/authority/file-type/XML>
> ]
> but the [SHACL file](https://github.com/SEMICeu/DCAT-AP/blob/b9b20d1d25e6d827754e93af918344a46dc41a1b/releases/2.0.1/dcat-ap_2.0.1_shacl_shapes.ttl#L603) expects the object to be of type dct:MediaTypeOrExtent which <http://publications.europa.eu/resource/authority/file-type/XML> is not. What should I use as an object for the above example?
> 

We took over the exact definitions for property "dct:format" from  DCAT-AP v2.0.1. 
The range is indeed the class "dct:MediaTypeOrExtent".  There are no further properties defined by DCAT-AP for this class, by the way.

The code proposal looks fine to me. Why do you think...

> but the  SHACL file expects the object to be of type dct:MediaTypeOrExtent which <http://publications.europa.eu/resource/authority/file-type/XML> is not. 

I see the SHACL does not contain any constraints about the usage of class "dct:MediaTypeOrExtent". So I see no problems.

**Comment by peterlubrich** [comment] 2024-08-15 13:00
> The property cnt:characterEncoding usage notes states that
> 
> A controlled vocabulary § 5.2 Controlled vocabularies to be used is provided.
> 
> but I cannot find one. And the range is defined as rdfs:Literal instead of it being a skos:Concept as with the other controlled vocabularies

This has been already resolved in [issue 34](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/34).

**Comment by marioscrock** [comment] 2024-08-26 09:45
Thank you @Joonas-M-S for the relevant points raised and @peterlubrich for the answers.

Regarding `mobilitydcatap:mobilityDataStandard`, I think the expected usage should be discussed and then clarified in the spec. In the example provided with our spec, we have

```turtle
<https://www.trafficdata.se/dataset/ec459578-a11f-4728-acaa-16b08ae45cfa/resource/4d2cccaf-219f-4fe6-a22c-d695ce86699d>
  a dcat:Distribution ;
  [...]
  mobilitydcatap:mobilityDataStandard <https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II> ;
```

In the RDF serialisation of the spec, we have `dcam:rangeIncludes` and not `rdfs:range` spec for the `mobilityDataStandard` property to enable both the adoption of this approach or the creation of a "custom value" as an instance of the class `MobilityDataStandard`. Regarding the first approach (in the example above), the serialisation can be slightly improved by also adding `dcam:rangeIncludes skos:Concept` for the `mobilityDataStandard` property, as done for other properties referencing a controlled vocabulary. Regarding the second approach an example is:

```turtle
<https://www.trafficdata.se/dataset/ec459578-a11f-4728-acaa-16b08ae45cfa/resource/4d2cccaf-219f-4fe6-a22c-d695ce86699d>
  a dcat:Distribution ;
  [...]
  mobilitydcatap:mobilityDataStandard <https://www.trafficdata.se/standard/datex-ii-se-profile-v3.2> .

<https://www.trafficdata.se/standard/datex-ii-se-profile-v3.2> a mobilitydcatap:MobilityDataStandard ;
  owl:versionInfo "3.2" ;
  mobilitydcatap:schema "...URL leading to schema file(s)..." .
```
The approach proposed by @peterlubrich in this issue (see [comment](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/35#issuecomment-2291087943)), I believe can **not** be used since it is not possible to associate properties directly to `https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II` that is a value that should be valid for everyone using the controlled vocab (e.g., also people using another version of Datex II). A custom instance of class `mobilitydcatap:MobilityDataStandard` should be defined (as shown above for `<https://www.trafficdata.se/standard/datex-ii-se-profile-v3.2>`). However, in this case, it is not clear to me what would be the best option to specify that this instance of `mobilitydcatap:MobilityDataStandard`, despite referencing a specific version/schema of Datex II, is somehow also related to `https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II`. Please let me know your comments.

Regarding the `dct:format` usage, I believe this is an issue "inherited" from DCAT-AP v2.0.1. Indeed, by reading their spec they use the property `dct:format` that has a specific range `dct:MediaTypeOrExtent` and then recommend the usage of the controlled vocab `http://publications.europa.eu/resource/authority/file-type` that contains concepts not defined as instances of the `dct:MediaTypeOrExtent` class. Also the problem related to the SHACL shape is inherited by the DCAT-AP v2.0.1 shape that we import in the mobilityDCAT-AP SHACL shapes. It seems to me the same is true also in DCAT-AP v3.0.0 so I am not sure how this "inconsistent" pair of constraints can be addressed (we may consider opening an issue on their repo to get an answer).

Actions to summarise the status:
- [ ] @Daham-Mustaf Solve typo of `owl:versionInfo` as `<dcam:domainIncludes` rdf:resource="http://w3id.org/mobilitydcat-ap#MobilityDataStandard"/>`  in the RDF serialization
- [x] @peterlubrich Fix "There are differet optiions ..." typo
- [ ] Clarify expected usage of `mobilitydcatap:mobilityDataStandard` and the relation with the associated controlled vocabulary
- [ ] Clarify expected usage of `dct:format` (optionally asking DCAT-AP maintainers)
- [ ] Update SHACL shapes accordingly, currently `mobilitydcatap:mobilityDataStandard` is expecting an individual of class `MobilityDataStandard`

**Comment by vlcinsky** [comment] 2024-08-29 19:38
@Joonas-M-S mentioned the `schema` property of `MobilityDataStandard`.

I will try to describe how DATEX II deals with schemas so that you may harmonize mobilityDCAT-AP with given practice.

# What to Expect Regarding `schema` in the Context of DATEX II

DATEX II has a comprehensive class model (which evolves within each major version) that includes models for multiple publications. DATEX II v3 currently supports about 23 publication types.

A publisher is expected to:
- Publish content according to a selected publication
- Provide an XML schema for the given publication
- Ensure that the schema is based on a profiled (simplified) publication class model

## Schemas for Class Model Namespaces

On the datex2.eu website, you can find schemas for various namespaces at [DATEX II XML Schema Downloads](https://docs.datex2.eu/downloads/modelv35/#datex-ii-xml-schema), where there are 15 schemas available. **WARNING:** These schemas do not reference "publication" but rather specific aspects of the class model. They are not schemas for specific publications; instead, they serve as building blocks supporting different namespaces.

Actual publication schemas use these schemas (via include) to build a simplified, profiled model of the given publication.

## Implicit Publication Schemas

One can take the DATEX II class model, select the intended publication, and (using a schema generation tool) retain all available details of the publication to generate a schema for it.

Such a schema could be considered an implicit one for a given publication type. However, using such a schema is considered bad practice because it retains much more complexity within the publication model/schema than is necessary for practical use.

## Explicit Publication Schemas

One should use the [webtool](https://webtool.datex2.eu) or a "schema generation tool," select the publication of interest, and profile it by selecting only the relevant parts for the intended use. This process generates a (profiled) XML (or other types, such as experimental ASN.1 and JSON) schema.

This is the schema that the publisher is supposed to publish, share with consumers, and adhere to, as it serves as a sort of contract for the intended data structures.

Note that these schemas often use "include," so they are not single files but may require multiple files.

For example, consider the Dutch SRTI profile (SituationPublication) with an entry schema file, [DATEXII_3_D2Payload_0.xsd](https://github.com/DATEX-II-EU/Profiles/blob/main/Version%203/NL/Profile%20for%20Safety%20Related%20Traffic%20Information%20(SRTI)%20created%20from%20in-vehicle%20data/schema/DATEXII_3_D2Payload_0.xsd), which includes many more schemas from this [folder](https://github.com/DATEX-II-EU/Profiles/tree/main/Version%203/NL/Profile%20for%20Safety%20Related%20Traffic%20Information%20(SRTI)%20created%20from%20in-vehicle%20data/schema).

## Variety of Publication Schemas for the Same Publication vs. Harmonization

Currently, we are in a situation where most publishers using the same publication (e.g., SituationPublication) use slightly different publication schemas. Publishers are supposed to provide these schemas, but they often fail to do so.

There are valid reasons for these differences, primarily the use of different location referencing methods and the publication of slightly different sets of traffic information classes (such as Accidents, Incidents, Roadworks, etc.).

You may even find multiple publication profiles from the same publisher, for example, one for road works and another for accidents and incidents. There are good reasons for this.

There is an ongoing effort to agree on common publication profiles, but it will take years before a significant number of publishers adopt them.

## Conclusions

Providing a (profiled) publication schema is essential for effective data exchange.

Currently, you should not expect DATEX II to offer a single schema per publication type. Instead, you should expect each provider to use one or two independent schemas per publication type.

When considering catalogues for schemas, be aware that in DATEX II v3, the `include` statement may require more than one XSD file for a single profile.

Other MobilityDataStandards may use the same or different approaches—I would need to consult with my colleague @burespe1 to clarify this for TPEG. The same would apply (with other experts) for NeTeX and SIRI.

I hope the description above clarifies the DATEX II reality related to publication schemas, enabling you to harmonize mobilityDCAT-AP with this practice.

Note that #41 proposes adding the `specificContentModel` property to `MobilityDataStandard`. One might derive an implicit publication schema from its value, but that is not the intended use (as using implicit publication schemas is considered bad practice). The purpose of the `specificContentModel` is to classify distributions to make finding them much easier.

**Comment by Joonas-M-S** [comment] 2024-10-17 10:33
Thank you all for the comments. They were very helpful and made clear that the way I showed `MobilityDataStandard` was wrong.

About this:

> However, in this case, it is not clear to me what would be the best option to specify that this instance of mobilitydcatap:MobilityDataStandard, despite referencing a specific version/schema of Datex II, is somehow also related to https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II. Please let me know your comments.

Could one use `skos:broader` property for this? `https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II` does not have `owl:versionInfo` and `mobilitydcatap:schema` properties (they are optional and I couldn't find them defined anywhere) and seems to represent the whole DATEX II concept. Then could the example just add `skos:broader` like so:

```
<https://www.trafficdata.se/standard/datex-ii-se-profile-v3.2> a mobilitydcatap:MobilityDataStandard ;
  owl:versionInfo "3.2" ;
  skos:broader <https://w3id.org/mobilitydcat-ap/mobility-data-standard/datex-II> ;
  mobilitydcatap:schema "...URL leading to schema file(s)..." .
```

**Comment by marioscrock** [comment] 2024-11-25 10:11
> Actions to summarise the status:
> 
> * [x]  @Daham-Mustaf Solve typo of `owl:versionInfo` as `<dcam:domainIncludes` rdf:resource="[http://w3id.org/mobilitydcat-ap#MobilityDataStandard"/>`](http://w3id.org/mobilitydcat-ap#MobilityDataStandard%22/%3E%60)  in the RDF serialization
> * [x]  @peterlubrich Fix "There are differet optiions ..." typo
> * [x]  Clarify expected usage of `mobilitydcatap:mobilityDataStandard` and the relation with the associated controlled vocabulary
> * [x]  Clarify expected usage of `dct:format` (optionally asking DCAT-AP maintainers)
> * [x]  Update SHACL shapes accordingly, currently `mobilitydcatap:mobilityDataStandard` is expecting an individual of class `MobilityDataStandard`

Last three items now addressed in #65.

@Daham-Mustaf did you fix the typo for  `owl:versionInfo`? (cf. https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/35#issuecomment-2291056884)

I think we can then close this issue and continue the discussion in #41 and #65

**Comment by peterlubrich** [comment] 2024-11-26 18:14
> We took over the exact definitions for property "dct:format" from DCAT-AP v2.0.1.

@Joonas-M-S : This is indeed out of our responsibility. Could you please repeat your question (about the proper range of  "dct:format") as a new issue at the [issue list of DCAT-AP](https://github.com/SEMICeu/DCAT-AP/issues)? Thanks

**Comment by Joonas-M-S** [comment] 2024-11-27 09:23
Created https://github.com/SEMICeu/DCAT-AP/issues/403

**Comment by Daham-Mustaf** [comment] 2024-11-28 18:58
@marioscrock 

The issue is in the SHACL shape definition for `mobilitydcatap:mobilityDataStandard` property in the Distribution shape. The current definition has conflicting constraints and incorrect syntax:

Current problematic definition:
```turtle
sh:pattern "https://w3id.org/mobilitydcat-ap/mobility-data-standard" ;
sh:Class mobilitydcatap:MobilityDataStandard  ;
sh:minCount 1 ;
sh:maxCount 1 ;
sh:path mobilitydcatap:mobilityDataStandard ;
```

Issues identified:
1. Conflicting constraints: Has both `sh:pattern` and `sh:Class`
2. Incorrect syntax: `sh:Class` should be lowercase `sh:class`
3. Mismatch with the ontology design where mobility data standards are defined as SKOS concepts

Proposed fix:
```turtle
sh:class skos:Concept ;
sh:nodeKind sh:IRI ;
sh:minCount 1 ;
sh:maxCount 1 ;
sh:path mobilitydcatap:mobilityDataStandard ;
sh:name "mobility data standard" ;
sh:description "This property describes the mobility data standard, as applied for the delivered content within the Distribution. A mobility data standard, e.g., DATEX II, combines syntax and semantic definitions of entities in a certain domain (e.g., for DATEX II: road traffic information), and optionally adds technical rules for data exchange. " ;
sh:severity sh:Violation ;
```

Changes made:
1. Removed `sh:pattern` constraint
2. Changed `sh:Class` to `sh:class`
3. Changed the class to `skos:Concept` to align with how mobility data standards are defined in the ontology
4. Added `sh:nodeKind sh:IRI` to ensure the value is an IRI reference

This aligns with how mobility data standards are defined in the ontology as concepts within the `https://w3id.org/mobilitydcat-ap/mobility-data-standard` concept scheme.
```

**Comment by Daham-Mustaf** [comment] 2024-11-28 19:00
Hi @marioscrock  for this isu Solve typo of owl:versionInfo as <dcam:domainIncludes rdf:resource="[http://w3id.org/mobilitydcat-ap#MobilityDataStandard"/>`](http://w3id.org/mobilitydcat-ap#MobilityDataStandard%22/%3E%60) in the RDF serialization I am not sure where is it! 
Could you please:
1. Point to the specific file where this typo exists?
2. Show the current problematic code snippet in context?

**Comment by peterlubrich** [comment] 2024-12-23 09:19
> @marioscrock
> 
> The issue is in the SHACL shape definition for `mobilitydcatap:mobilityDataStandard` property in the Distribution shape. The current definition has conflicting constraints and incorrect syntax:
> 
> Current problematic definition:
> 
> ```turtle
> sh:pattern "https://w3id.org/mobilitydcat-ap/mobility-data-standard" ;
> sh:Class mobilitydcatap:MobilityDataStandard  ;
> sh:minCount 1 ;
> sh:maxCount 1 ;
> sh:path mobilitydcatap:mobilityDataStandard ;
> ```
> 
> Issues identified:
> 
> 1. Conflicting constraints: Has both `sh:pattern` and `sh:Class`
> 2. Incorrect syntax: `sh:Class` should be lowercase `sh:class`
> 3. Mismatch with the ontology design where mobility data standards are defined as SKOS concepts
> 
> Proposed fix:
> 
> ```turtle
> sh:class skos:Concept ;
> sh:nodeKind sh:IRI ;
> sh:minCount 1 ;
> sh:maxCount 1 ;
> sh:path mobilitydcatap:mobilityDataStandard ;
> sh:name "mobility data standard" ;
> sh:description "This property describes the mobility data standard, as applied for the delivered content within the Distribution. A mobility data standard, e.g., DATEX II, combines syntax and semantic definitions of entities in a certain domain (e.g., for DATEX II: road traffic information), and optionally adds technical rules for data exchange. " ;
> sh:severity sh:Violation ;
> ```
> 
> Changes made:
> 
> 1. Removed `sh:pattern` constraint
> 2. Changed `sh:Class` to `sh:class`
> 3. Changed the class to `skos:Concept` to align with how mobility data standards are defined in the ontology
> 4. Added `sh:nodeKind sh:IRI` to ensure the value is an IRI reference
> 
> This aligns with how mobility data standards are defined in the ontology as concepts within the `https://w3id.org/mobilitydcat-ap/mobility-data-standard` concept scheme.

This has been resolved in combination with [issue #65](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/65)

**Comment by peterlubrich** [comment] 2024-12-23 09:30
> Hi @marioscrock for this isu Solve typo of owl:versionInfo as <dcam:domainIncludes rdf:resource="[http://w3id.org/mobilitydcat-ap#MobilityDataStandard"/>`](http://w3id.org/mobilitydcat-ap#MobilityDataStandard%22/%3E%60) in the RDF serialization I am not sure where is it! Could you please:
> 
> 1. Point to the specific file where this typo exists?
> 2. Show the current problematic code snippet in context?

I have repaired the [RDF serialisation for the v1.1.0 draft](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/gh-pages/drafts/latest/serialisationFiles/mobilitydcat-ap.rdf), no more typos!

**Comment by peterlubrich** [comment] 2024-12-23 09:31
All the To-Dos above are resolved, closing this issue!

**Closed as completed** 2024-12-23 09:30 UTC
Labels: enhancement, question
